### ISSUE TITLE
Disk consumption issue

### ISSUE THREAD

**Issue by sjiribarren** [uwcirg/tb-mobile-app#141]
Notes from John Howe: disk consumption issue. 
docker container tb-mobile-app_web_1 still continues to eat disk space at gigs/day. It logs into /var/lib/docker/containers/$CID/$CID-json.log. I seem to have to restart docker manually every week or so to manually clear this log. I’m basically cp /dev/null your logs, so that’s pretty heavy handed solution. Stylistically, logging into a container seems bad practice to me, it should be a mapped volume.
I think it requires a minor refactor of the docker-compose files and probably setting up a couple logrotate.d rules.

**Comment by kylegoodwin** [comment]
Closing this issue, and breaking it up into separate ones. It is a more complex problem than expected.
