### ISSUE TITLE
Translations unavailable offline

### ISSUE THREAD

**Issue by kylegoodwin** [uwcirg/tb-mobile-app#164]
Can edit service worker configuration to cache /locales/en/translation.json or not use XHR based translation import.

**Comment by kylegoodwin** [comment]
https://github.com/uwcirg/tb-mobile-app/blob/96e4dc92992632ff33d183f1bd252b7eaa437afe/public/custom-service-worker.js#L22-L24

Edited this to cache json - but this means that the language must be loaded first.

Will have to evaluate going forward - might be worth it to ditch the XHR model and import translations directly.

**Comment by ivan-c** [comment]
>ditch the XHR model and import translations directly

@kylegoodwin That's what we're doing for [TrueNTH (gulpfile here)](https://github.com/uwcirg/truenth-portal/blob/develop/portal/i18next_gulpfile.js), building the translations into the front-end app.

I really don't understand why retrieving them dynamically (via XHR) would be better. Maybe so languages can be dynamically added to the back-end?

**Comment by kylegoodwin** [comment]
Ya thats what I was thinking, I think the documentation I was following to get it set up configured it with XHR. I will reconfigure it to load directly going forward.

**Comment by kylegoodwin** [comment]
Fixed in  6ad093e219d5c2e1e52109f3d84b87c19d01edb4
