### ISSUE TITLE
Update `yarn` to `> 1.1.0' to remove security warning

### ISSUE THREAD

**Issue by thecalliopecrashed** [uwcirg/tb-mobile-app#18]
As mentioned in #17, `docker build -t client .` gives us a warning about a deprecated `Buffer` constructor that contained security flaws.

The warning message was addressed by the `yarn` community [here](https://github.com/yarnpkg/yarn/issues/5477#issuecomment-412064714), and to fix in our own app we need to upgrade our `yarn` version.

Any version above `1.1.0` should be okay.

**Comment by jacobq** [comment]
(v1.**10**.0)

**Comment by thecalliopecrashed** [comment]
ah, thanks for catching that!

**Comment by thecalliopecrashed** [comment]
This is outdated;

```bash
> docker-compose exec client yarn -v
1.13.0
```

We haven't seen a security warning in a while.
