### ISSUE TITLE
Medical icons

### ISSUE THREAD

**Issue by c4lliope** [uwcirg/tb-mobile-app#237]
Inspiring, if nothing else.
https://iconify.design/icon-sets/medical-icon/

![Screen Shot 2021-03-26 at 3 29 51 PM](https://user-images.githubusercontent.com/30454698/112683558-1f5e5f00-8e48-11eb-91cd-9112765495f2.png)

**Comment by c4lliope** [comment]
`i-pharmacy` and `i-registration` may be usable.
I'm exploring Iconify as a replacement for `@mdi/react` and `@mdi/js` packages, it seems nice and approachable,
and the library support is endless.

**Comment by kylegoodwin** [comment]
Thanks for sending, we mostly use material-ui/icons for basic UI icons, and adapt ones from this website for more visual flair https://undraw.co/illustrations
