### ISSUE TITLE
Mock up new survey flow

### ISSUE THREAD

**Issue by thecalliopecrashed** [uwcirg/tb-mobile-app#30]
* [x] Move date numbers into top-left corner
* [x] Stack icons vertically
* [x] highlight incomplete days (green/red)
* [ ] countdown of 6 months' progress (migrated to #42)
* [x] disable clicking on future dates
* [ ] Stretch: don't require photo upload every day, change requirements as patients progress through their regimen. (migrated to #53)

**Comment by sjiribarren** [comment]
Few thoughts from playing with current version:
Calendar/reporting screen
- keep icons same size and in the same location even if only report one thing
- could a pill icon be used for med report? maybe box for symptom or another icon?
- maybe add a key for icons at bottom?
- in Latin America the calendars start on Monday - see example in Notion Feature inventory
- change calendar color to white
- will work on translation/text later
Login
- Will need place to log start date for the countdown to treatment completion
Information
- change display of options. boxes? can simplify labels

**Comment by sjiribarren** [comment]
Patient interface functions
- [ ] Reporting (?) - simplify process from field test model
	- [ ] Daily medication (?)
             - [ ] If no --> reason unable to take medication: fill in the blank
	     - [ ] OR survey on difficulty taking medication: transportation, forgot, tired, side effects, other… (see example in the Feature Inventory)
	- [ ] Daily symptoms (?)
		- [ ] Reduce dead space - Move the text closer to the check boxes 
                - [ ] Pop up message for high risk symptoms 
                - [ ] images of symptoms (see feature function file) ( would be nice but not priority)
	- [ ] Urine test
		- [ ] Add back in test taking / image capture Instructions (?)
                - [ ] easy image upload
                - [ ] feedback that image was received
                - [ ] future - read images after accumulate patient created library
- [ ] Progress
        - [ ] Count down/clock/ from start date - Grace found website with examples
        - [ ]  list of symptoms report
- [ ] Information/ Education
	- [ ] FAQ - fix drop down boxes
        - [ ] Side effects - Large bold font --> make same font as FAQ page
        - [ ] How best to push Treatment stage appropriate educational messages - 2x/week
        - [ ] Patient recommendations to others - upload patient recommendations to others starting
- [ ] Notes
        - [ ] alert or note that viewed by study/treatment coordinator
- [ ] Communication
        - [ ] WhatsApp - trial otherwise need to rethink notes
                  - [ ] Send request for access as research project
Pop up
- [ ] Changeable messages: e.g., Welcome, Thank you for submitting, keep it up, # of consecutive days reporting taking medication

Provider/coordinator interface
- [ ] Alert for not reporting taking medication
- [ ] view communication with patients in provider interface or WhatsApp platform?
- [ ] order of features in this list reflects the patient flow through the reporting screens


Other
- [ ] New URL for easy access (purchase a name)
- [ ] Sarah to translate
- [ ] Fernando to verify translation

**Comment by thecalliopecrashed** [comment]
Symptom list:
a lot of space between boxes and actual symptoms.

Tested, functional, langauge-clean

* Photo upload
* Provider interface
* WhatsApp

Sarah's gone on the 28th and 29th.

30 days

* Set up a time with Bill.
* We want this to be built for

Pingdom

https://comotion.uw.edu/contact-us/

- - -

Risk Registry
Top 5 potential problems

1.
2.
3.

responses to that problem.

- - -

**Comment by thecalliopecrashed** [comment]
Alright!
I broke out ~25 other issues to capture the tasks listed here.
Links to new issues are listed inline in the comments above.
Closing this issue. 🎉
