### ISSUE TITLE
[coordinator] Daily review screening of patients

### ISSUE THREAD

**Issue by thecalliopecrashed** [uwcirg/tb-mobile-app#41]
* Label patients as "Needs action" / "Review" / "No action necessary",
* color indications (green/red)
* Alert for patients who have not taken medication (noon cutoff)
* view communication with patients

**Comment by thecalliopecrashed** [comment]
May be some overlap with #62 .

**Comment by campbellsean** [comment]
Closing as a duplicate to #62
