### ISSUE TITLE
Improve mobile view of adherence breakdown

### ISSUE THREAD

**Issue by kylegoodwin** [uwcirg/tb-mobile-app#412]
Current state:
<img width="200px" src="https://user-images.githubusercontent.com/10137989/176742813-a5279ee6-ebda-4c91-9776-87d08a4ba92e.png" />

Update from Alfie:
<img width="200px" src="https://user-images.githubusercontent.com/10137989/176742942-0897bbc6-a073-427b-9f78-ae72dc7833e5.png" />

**Comment by johnny2smooth** [comment]
I've made the changes that I can to get as close as possible to Alfie's mock up. I need a few things for higher fidelity:

-MUI icons doesn't have a pill / medication icon for some reason
- We don't have a shortened translation for 'Meds.'. If we use the full 'Medication' string, the layout breaks and the percentage is pushed  to the next line.
- ^^ we can workaround this by just using icons, then implementing name as an alt tag.

**Comment by kylegoodwin** [comment]
Good point John - I think it makes sense just to do what you said with the icons. Not sure that you will be able to add an alt tag because the Icons are implemented as SVG tags.

There is a Medication Icon that we added in custom - check src/Basics/Icons/Pill.js

**Comment by johnny2smooth** [comment]
Pill SVG added. Both SVGs alt tags are translated as well.

**Comment by kylegoodwin** [comment]
Closed in ea960ba477ae809b92e500898d4e48aff96567ad
