### ISSUE TITLE
Patient History (display for patient on mobile)

### ISSUE THREAD

**Issue by thecalliopecrashed** [uwcirg/tb-mobile-app#42]
* percentage of treatment
* accordians for events
* display "Positive"/"Negative" for test results

**Comment by thecalliopecrashed** [comment]
countdown of 6 months' progress

**Comment by campbellsean** [comment]
Shows:

* days reported in a row and record of days reported in a row
* progress circle with % of treatment completed

Anything else?

**Comment by campbellsean** [comment]
1) Days in a row with a number and a bar
2) Days left starting from 180 and going down. No percentages for the patient.

Symptom history on the progress page

**Comment by campbellsean** [comment]
Instead:
- Fill the circle up to 180 days of treatment
- What they report for side effects for that date
- Treatment Reported, a line with a drop down arrow to see what they scrolled

3 Rows with a toggle to see past dates

**Comment by thecalliopecrashed** [comment]
#78 is merged!
