### ISSUE TITLE
Link to patient message thread in WhatsApp

### ISSUE THREAD

**Issue by thecalliopecrashed** [uwcirg/tb-mobile-app#48]

**Comment by campbellsean** [comment]
Note to assign this to me.

**Comment by thecalliopecrashed** [comment]
![image15](https://user-images.githubusercontent.com/30454698/52299622-bac7a980-293a-11e9-8162-165387348939.png)

This was the original mockup for the notes feature.

We were trying to bridge the gap between private notes, and coordinator messaging.
This would be a straightforward way for patients to keep a note private
until they're ready to share it with their coordinator.

It's not clear if this UI still makes sense, though -
it's very thread-based,
and we've been talking about a more chat-like UI with a continuous stream of messages.

**Comment by sjiribarren** [comment]
This was the first mock-up of messaging based on a similar design as WhatsApp

**Comment by thecalliopecrashed** [comment]
We had a lot of activity on this during our check-in.

Sean (@campbellsean) was able to send WhatsApp messages through a web browser;
we can construct links in the form `https://wa.me/12345678900`,
which will open a browser chat interface to the phone number in the link.

If we place links like the above into the coordinator interface,
we'll be able to ferry the coordinators to a dedicated,
encrypted (through WhatsApp)
conversation with their patient.

The patient will receive messages directly in WhatsApp – 
their preferred communication channel.

The coordinators will need to sign in to WhatsApp
before they can message the patient.
To do this, they must install WhatsApp on their phone.

<img width="952" alt="screen shot 2019-02-07 at 2 07 27 pm" src="https://user-images.githubusercontent.com/30454698/52446069-cacdbd80-2ae1-11e9-95c3-a6dade8f312c.png">

We may be able to set up a [WhatsApp Business account](https://www.whatsapp.com/business/)
so that coordinators don't have to sign in with their personal phone numbers.
However, it's not definitive if that will scale beyond a single coordinator device.

### Maintenance: Title change

This direction is a clean break from the note-taking function;
we won't be making any changes to that code under this issue.

Instead, the current code for notes
will likely get folded into patient-to-patient communication,
discussed in #61.

Changing this title to "Send directed messages to patients through a browser".

**Comment by thecalliopecrashed** [comment]
Presented in our check-in; waiting for merge.
