### ISSUE TITLE
Display test results to participants

### ISSUE THREAD

**Issue by thecalliopecrashed** [uwcirg/tb-mobile-app#49]
Don't yet have support for push notifications.

**Comment by thecalliopecrashed** [comment]
My progress page; see #42.

A confirmation that the coordinator saw and classified the test result.

**Comment by thecalliopecrashed** [comment]
Display `yes/no` result on patient's "My Progress" page;
it's coming through as `null` now.

**Comment by campbellsean** [comment]
Closed by #99
