### ISSUE TITLE
Survey Design

### ISSUE THREAD

**Issue by pmanko** [uwcirg/tb-mobile-app#5]
Link to design outline: 

with hierarchy:
https://qub7qk.axshare.com/#g=1&p=startup_page

without hierarchy:
https://qub7qk.axshare.com/#p=startup_page&g=0

Survey content:
https://docs.google.com/spreadsheets/d/1rmK8cOURVNdIbRM5z3HQwNDBJPUi1UBK6I_tG-4uDws/edit?usp=sharing

**Comment by pmanko** [comment]
![img_20180226_120702](https://user-images.githubusercontent.com/711826/36692792-ee48379a-1aed-11e8-8b67-b26d6dc78212.jpg)

**Comment by pmanko** [comment]
@ivan-c see the following issue: #3 

@sjiribarren mentioned we should focus on the spanish version of the questions. Could you use the spanish translations instead of the english content for the questions?

**Comment by ivan-c** [comment]
@pmanko @sjiribarren 
The translation framework we use inside cPRO (GNU Gettext) is configured to expect English as a source language, and would require significant effort to switch.

However, I've finished the content of the survey so we can start adding translations immediately if you're willing.

[Here is a gettext file with the English Daily Check-in strings](https://gist.github.com/ivan-c/814a5034f0b23a8c375ab6cc4466b319), if you add translations I should be able to add the resulting file to the codebase.

I occasionally use the windows desktop application, [PoEdit](https://poedit.net/), but this [online version should work as well](https://localise.biz/free/poeditor)

**Comment by sjiribarren** [comment]
How do I add the translations? Below, replace?
thanks


SARAH J. IRIBARREN, PhD, RN

Assistant Professor, Biobehavioral Nursing and Health Informatics
University of Washington, School of Nursing
HSB, Box 357266
1959 NE Pacific Street, T618A, Seattle, WA 98195-7266
Tel: 206.543.5211/ Fax: 206.543.4771
sjiribar@uw.edu<javascript:_e(%7B%7D,'cvml','sjiribar@uw.edu');>

**Comment by ivan-c** [comment]
@sjiribarren 
Ideally, you would use a tool for working with Po files to avoid breaking the file formatting. However, they are still plain text files and you can add translations to the file without a po-specific editor by inserting the translation between the quotes on the `msgstr ""` lines.

If you would like to use [the online Po editor](https://localise.biz/free/poeditor):
* Download the file (saving as `mpower_tb_db.pot`; file suffix matters)
* Upload to [Poeditor](https://localise.biz/free/poeditor)
* Select a string from the list
* Add translation to box beneath **Unknown translation**
* Save

**Comment by sjiribarren** [comment]
Sorry – having issue saving to as you instructed.  I tried downloading the ZIP option and it is recognized as a PPP or not recognized by my computer and I tried saving the Raw data. Advise?
Thanks
Also that is only the first stage of the survey.  There are other survey components (e.g., symptom/side effects, photo/test strip). Maybe each survey is done separately?


SARAH J. IRIBARREN, PhD, RN

Assistant Professor, Biobehavioral Nursing and Health Informatics
University of Washington, School of Nursing
HSB, Box 357266
1959 NE Pacific Street, T618A, Seattle, WA 98195-7266
Tel: 206.543.5211/ Fax: 206.543.4771
sjiribar@uw.edu<javascript:_e(%7B%7D,'cvml','sjiribar@uw.edu');>

**Comment by ivan-c** [comment]
@sjiribarren 
Sorry, I should've included those details:


[Download ZIP](https://gist.github.com/ivan-c/814a5034f0b23a8c375ab6cc4466b319/archive/657c68342ea544d422c288d798593fa9535d8cd8.zip) should work, you'll just have to extract and upload the file inside the archive.

The file should be called `mpower_tb_db.pot`, inside a folder named `657c68342ea544d422c288d798593fa9535d8cd8`. 

Then, drag and drop the file into the Po edit site

(Your computer will probably erroneously recognize it as a PowerPoint file, but if you want to sanity check it, use TextEdit to open/view.)

**Comment by sjiribarren** [comment]
Hi Ivan,

I finished adding the translations and saved.  I am hoping that you will be able to access it in your account.  Otherwise here is the attachment that I downloaded.  I hope...  Will have this down the next go around.

thank you

Sarah

________________________________

**Comment by ivan-c** [comment]
@sjiribarren 
Looks like the attachment didn't come through, could you email it directly to me at ivanc@uw.edu ?

Thanks!!

**Comment by ivan-c** [comment]
@sjiribarren @pmanko 
Where can I find information about the dose scheduling? I need to know how to calculate the dose times used in the survey (eg `%(next_dose_time)`).

What time-point (registration, first dose, first survey, appointment) should be used for calculating the subsequent doses?

Thanks!

**Comment by sjiribarren** [comment]
Should be first dose and then from each prior dose reported. It might not be anywhere from before

________________________________________

**Comment by ivan-c** [comment]
[Added daily check-in assessment, translations](https://gitlab.cirg.washington.edu/svn/dhair2/merge_requests/28); dynamic/conditional text still WIP

**Comment by thecalliopecrashed** [comment]
Outdated; translations are in place. Archiving.
