### ISSUE TITLE
Instructions for uploading test strip image

### ISSUE THREAD

**Issue by thecalliopecrashed** [uwcirg/tb-mobile-app#56]
La prueba de orina asegura que su tratamiento esté en camino.
Por favor siga estas instrucciones:

1. orinar en la taza;
2. corta el extremo de la paja a lo largo de la línea punteada
3. poner el extremo abierto de la pajilla en la orina y dejarla.
4. espere 5-15 minutos para tomar la fotografía (una vez que vea un cambio claro en el color);
5. haga clic en Iniciar. Toma la foto (retome la imagen si está borrosa u oscura);
6. asegúrese de ver la marca de verificación () y seleccionar Adelante para finalizar la carga.

**Comment by thecalliopecrashed** [comment]
- [ ] easy image upload
- [ ] feedback that image was received (check mark or other indicator)
- [ ] future - read images after accumulate patient created library

**Comment by thecalliopecrashed** [comment]
Previous versions of the translations can be found on #12.

**Comment by sjiribarren** [comment]
Instruction modification if you are able to add the timer:
English:
The urine test confirms that you are taking your medication as instructed. 
Please follow these instructions to take the test:
1)	Void in a cup
2)	Cut the end of the straw with the test strip along the line
3)	Place the cut end of the straw with the test strip into the urine and START timer
4)	Wait for 5-15 minutes (no more than 20) to take the picture (once you see a clear color change)
5)	Select TAKE picture. Take the picture (retake if blurry or dark)
6)	Be sure the check mark (check mark or other?- image not coming through here) appears for uploaded successfully and select Continue to finish

Spanish
La prueba de orina asegura que su tratamiento esté en camino. 
Por favor siga estas instrucciones: 
1)	orinar en la taza; 
2)	corta el extremo de la paja a lo largo de la línea punteada
3)	poner el extremo abierto de la pajilla en la orina y iniciar el cronómetrodejarla.
4)	Eespere 5-15 minutos (no más de 20) para tomar la fotografía (una vez que vea un cambio claro en el color); 
5)	haga clic en Iniciar. Toma la foto (retome la imagen si está borrosa u oscura); 
6)	asegúrese de ver la marca de verificación () y seleccionar Adelante para finalizar la carga.
