### ISSUE TITLE
Secure the app

### ISSUE THREAD

**Issue by thecalliopecrashed** [uwcirg/tb-mobile-app#60]
https://jwt.io

**Comment by lober** [comment]
This was the thread in slack pertaining to authentication https://cirg.slack.com/archives/CC0V4G370/p1548967545017100

**Comment by thecalliopecrashed** [comment]
Okay, migrating a portion of the conversation about OAuth providers.

> The foundation currently provides only sample information from the database.
We will need to add a hook, so the authentication credentials pull the correct object
from the database.

The "sample information" here could use some clarification.
The main lacking component in the foundation right now
is identity lookup; it's something that is handled with sample information now,
and can be expanded to support many protocols in the future.

The "hook" in question would execute *after* credentials have been received and verified.

> This could be done in the foundation,
but that would require the foundation to know application-specific information:
how to look up the patient record.

"patient" specifically, "identity" generally.

> It is a bit cleaner to add code client-side,
which will load account information upon request.

Again, this code stored on the client-side can only execute after credentials have been verified.

This has the effect that for the Tuberculosis assembly,
patients will effectively submit "instructions" on how to look up their records.

In order to prove that the instructions are valid,
the server would compare the code's cryptographic signature against a reference
before executing them.

For instance, a patient might proceed through the OAuth2 flow.
At the end, the server recognizes the credentials
as belonging to a participant in the TB Argentina study.

Now, the bearer of the credentials submits code to be run against the application database.
The bearer vouches that the code, `Patient.find_by(id: 12345678)`,
can be used to locate the patient's record.

Here, the server-side component needs to determine if the code is safe to execute or not.

It compares the submitted instructions, `Patient.find_by(id: 12345678)`
to a list of authorized commands that can be run against the database.
It finds a record, `Patient.find_by(id: ${authorization_token})`.
(Javascript string templating used for reference; other templating options available).

**Comment by thecalliopecrashed** [comment]
The operator(s) of the application, in this case Sarah,
would be able to log in and approve the code execution attempts that come in.

After a brief initial setup,
arbitrary code snippets from development could be quickly approved and executed
against the production environment.

**Comment by thecalliopecrashed** [comment]
0. Generate an RSA public/private key pair for the foundation.
1. Serve the RSA public key from the server.
2. Load the RSA private key into the server, but do not reveal it publicly.

On Registration:

* Collect
  ```
  {
  "initials": "GCY",
  "date_of_birth": "1992-01-01",
  "study_start_date": "2019-02-11",
  "study_participant_id": "abc123"
  } 
  ```
* Take provided sign in information and server's public RSA key, and encode into a JWT.
* Store the JWT in the browser's storage, for the participant's next session.
* Send JWT to the server.
* Server: decode JWT using the server's private RSA key.
* Server: Allow app use, pending approval of registration information.

**Comment by thecalliopecrashed** [comment]
@lober and @ivan-c - please bear with as I capture some of the security issues at play here.

- - -

## Future: Encrypted Tokens

The goal of these tokens is to anonymize the data that we collect,
through a single "Identity" data point.

HIPAA and other healthcare regulations require that healthcare information be stored separately from "Personally Identifiable Information" (PII).

In our case, healthcare information the study data; everything stored in our database.
It is most useful for us to keep this information unencrypted, so we can access it in the app and during analysis.

That means that we really should not store personally-identifiable participant information in the database as well; developers would be able to pair together PII with health data arbitrarily.

Instead, we can encrypt the identity information to make sure that only authorized parties can access and view someone's identity.

- - -

## Present: Transparent Tokens

I had hoped to implement encrypted personal identities through JSON web tokens,
but there turn out to be an issue:

JSON web tokens are not designed to keep data private.
Instead, they're used instead to point to a source for public information.

> The difference is that if we ever "leak" an encrypted token to someone without authority,
they would not be able to retrieve identity information from it.

> If we "leak" a JSON web token to someone without authority, retrieving the information is as simple as pasting the token into https://jwt.io.

We collect this information during registration:

```
{
"initials": "GCY",
"date_of_birth": "1992-01-01",
"study_start_date": "2019-02-11",
"study_participant_id": "abc123"
}
```

If this data is not too sensitive,
and if we think the chance of leaking this data is low enough,
then JSON web tokens remain a solid approach.

Each patient would "vouch" for their information on registration,
and the token would become a kind of receipt for them;
it could be used to retrieve their account or information.

Any change to a user's personal information
would require getting a new token from the server,
which would represent a new account for the participant.

Since we don't expect participant's registration information to change, this isn't a major issue.
We simply don't allow patients to modify their registration information,
and then we can use JWTs as a *permanent, unchanging, and internal-to-the-code* token
that never gets presented to the user.

- - -

## Aside: Oauth

After looking into #59, it turns out that Oauth is not designed for client/server authentication.

The main use of OAuth online today is to log into websites using social media account information.
In that case, the social media network relays your personal information to the target website;
for example, your email address and your contact list.

Adding an OAuth provider into our application wouldn't hurt us,
but we would use it to share information with third-party applications.
It would not be able to solve our immediate problem:
securing connections between our server, and participants' mobile devices.

**Comment by lober** [comment]
@thecalliopecrashed  - Sarah told me she asked you to post this ticket in #tb-dev.   I think a number of comments in your Aside: Oauth might not be accurate.  Sorry for the delay - I didn't realize that you were asking for feedback.

1) OAuth2 can authenticate client/server connections.   I think you can google "oauth client server" for a number of examples.

2) an OAuth provider can be either a public provider (GoogleID, Facebook, OpenID) or it can be a private OAuth provider (a MS Active Directory, or TrueNTH's OAuth IDP, or cPRO's patient database acting as an IDP, etc.).
