### ISSUE TITLE
[discussion] patient-to-patient communication

### ISSUE THREAD

**Issue by thecalliopecrashed** [uwcirg/tb-mobile-app#61]
Patients have expressed a desire to "exchange information / recommendations with other patients". (#20)

This does not seem to be a mission-critical feature, but might benefit from additional discussion.

**Comment by sjiribarren** [comment]
correct - not mission critical. An alternative could be a place in the Info/Education tab where we post a list of comments and recommendations from other patients.  I think this could be helpful and an easy alternative for the time being

**Comment by campbellsean** [comment]
Closing because of Discourse set up @ https://tb-discourse.cirg.washington.edu/
