### ISSUE TITLE
Tame the Coordinator Interface

### ISSUE THREAD

**Issue by thecalliopecrashed** [uwcirg/tb-mobile-app#62]
This issue aims to define the particulars of the coordinator interface.

* Specific behaviors and interactions.
* Information that coordinators expect.
* Abstract: managing consent

We will build on the work already done in wireframes,
in the previous implementation built on cPRO systems,
and on the current implementation in `/src/components/CoordinatorHome.js`.

<img width="1168" alt="screen shot 2019-02-07 at 12 18 42 pm" src="https://user-images.githubusercontent.com/30454698/52447051-8abc0a00-2ae4-11e9-9fd6-71479be8641a.png">
(Names in image are semi-randomly generated by https://rubygems.org/gems/faker)

**Comment by thecalliopecrashed** [comment]
* [ ] Link to patient history page
* [ ] For each uploaded photo, mark as "Positive" or as "Negative/Unclear"
* [x] link to Patient chat in WhatsApp

**Comment by campbellsean** [comment]
Closed with #71
