### ISSUE TITLE
[Coordinator] Show individual patient history

### ISSUE THREAD

**Issue by thecalliopecrashed** [uwcirg/tb-mobile-app#64]
Related to #42.

**Comment by campbellsean** [comment]
Allows the coordinator to look into the patients history of reporting. Pops up as a modal.

**Comment by campbellsean** [comment]
@thecalliopecrashed is it possible to record last log in?

**Comment by campbellsean** [comment]
CUT % of Adherence
- 30/50 is 60% adherence for the coordinator

Add a column for the amount of days since last reporting.

**Comment by campbellsean** [comment]
@sjiribarren let me know about days since last report vs. % adherence
