### ISSUE TITLE
Icon to save app to homepage

### ISSUE THREAD

**Issue by sjiribarren** [uwcirg/tb-mobile-app#65]
Designate icon appearance. 
Ensure that icon successfully opens the web app home page. 
Standardize and document the home screen icon saving process so that coordinators can help patients set up on first-time registration.

**Comment by campbellsean** [comment]
For iPhone -> https://www.create.net/support/adding-an-ios-home-screen-icon-for-your-website

**Comment by campbellsean** [comment]
Closed by #99 also added Android white app logo with rounded corners
