### ISSUE TITLE
Mobile app design and styles

### ISSUE THREAD

**Issue by pmanko** [uwcirg/tb-mobile-app#8]
## To Do
- [x] Global Styles
- [x] Home Page
- [x] Login Page
- [x] Bottom menu
- [x] Daily Check-in
- [x] My Progress

## Style guide
[TB app style guide.pdf](https://github.com/uwcirg/tb-mobile-app/files/1764284/TB.app.style.guide.pdf)

### English
https://qub7qk.axshare.com/#g=1&p=startup_page - with view of hierarchy
https://qub7qk.axshare.com/#p=startup_page&g=0 - without view of hierarchy

### Spanish
With hierarchy view: https://tsu9d5.axshare.com/#g=1&p=startup_page
Without hierarchy view: https://tsu9d5.axshare.com/#p=startup_page

**Comment by loreleileigh** [comment]
Important note - for the sake of time, we've been focusing our updates on the Spanish version of the prototype, so it is the most recently updated~ I'll change the hierarchy back to English right now so you guys will have an easier time navigating it :) 
With hierarchy view: https://tsu9d5.axshare.com/#g=1&p=startup_page 
Without hierarchy view: https://tsu9d5.axshare.com/#p=startup_page
