### ISSUE TITLE
Color revision

### ISSUE THREAD

**Issue by thecalliopecrashed** [uwcirg/tb-mobile-app#80]
Green: rgba(88, 185, 157)

**Comment by thecalliopecrashed** [comment]
![image 1](https://user-images.githubusercontent.com/30454698/53437371-31901980-39b2-11e9-8d1d-34b033362ee6.png)
![Uploading image.png…]()

**Comment by thecalliopecrashed** [comment]
Duplicate of #79

**Comment by thecalliopecrashed** [comment]
![image](https://user-images.githubusercontent.com/30454698/53437386-42408f80-39b2-11e9-914e-75c00ca40388.png)

**Comment by campbellsean** [comment]
Duplicate - use #79
