### ISSUE TITLE
Ending a note with a `\` acts as an escape sequence on the server

### ISSUE THREAD

**Issue by thecalliopecrashed** [uwcirg/tb-mobile-app#94]
Right now the note won't save, but this raises a larger (mostly moot right now) security issue.

This isn't something to fret over, but it is something that we should record and tackle later.

**Comment by thecalliopecrashed** [comment]
Try to URL encode our inputs before we submit it to the server.

**Comment by kylegoodwin** [comment]
Addressed in commit 3a7e583
